# Generated by Django 5.1.3 on 2024-11-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursos',
            field=models.ManyToManyField(related_name='alunos', to='Alunos.curso'),
        ),
    ]
