# Generated by Django 5.1.3 on 2024-11-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0002_curso_aluno_cursos'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aluno',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
